sitemap_urls:
  - "http://atelewo.org/post-sitemap.xml"

custom_settings:
  ROBOTSTXT_OBEY: false
  JOBDIR: "crawls/atelewo_spider"
  CONCURRENT_REQUESTS: 32
  OUTPUT_FILE: "data/atelewoorg.jsonl"
  ITEM_PIPELINES:
    otelemuye.pipelines.JsonWriterPipeline: 300